[theme]
base               = "light"
primaryColor       = "#4a3ee6"
backgroundColor    = "#f7fafd"
secondaryBackgroundColor = "#ebeef1"
textColor          = "#181c1e"
font               = "sans serif"

[server]
headless = true
